### ISSUE TITLE
LoginRequired

### ISSUE THREAD

**Issue by arjankapteijn** [jorisvandesande/unifi-api-client#1]
The $apiClient->login() works, I retrieve an csrf_token & unifises in my cookiejar but I cannot execute any commands like $apiClient->authorizeGuest():

Client error: 401 ----- Request ------ ----- Response ------ { "data" : [ ] , "meta" : { "msg" : "api.err.LoginRequired" , "rc" : "error"}}

The statistics function is working as expected / correct! 

What am i missing here? Maybe changes to Unify 4.7.6?

**Comment by jorisvandesande** [comment]
Maybe the user does not have the correct permissions tot authorize a guest. Are you using a read only user?

Does the statisticus call work?

**Comment by arjankapteijn** [comment]
I'm using an admin user. The http://dl.ubnt.com/unifi/4.7.6/unifi_sh_api works as expected. Statistics call works.

**Comment by jorisvandesande** [comment]
I do not use the authorizeGuest call myself. I will try to look into it in a couple of days.

**Comment by jorisvandesande** [comment]
It took me some time to figure out what the problem was. But it's fixed now.
