### ISSUE TITLE
Can't install library and no releases

### ISSUE THREAD

**Issue by calledit** [jorisvandesande/unifi-api-client#4]
Trying to install:

php composer.phar require jorisvandesande/unifi-api-client

[InvalidArgumentException]
  Could not find a version of package jorisvandesande/unifi-api-client matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.

And there is no release on the github release page.

**Comment by malle-pietje** [comment]
Honestly, not meaning to hijack this repo (I particularly like the Guzzle use) but I'm afraid it's not actively maintained. Instead, you could consider using this client class which I maintain: https://github.com/Art-of-WiFi/UniFi-API-client

**Comment by jorisvandesande** [comment]
You could try: `php composer.phar require jorisvandesande/unifi-api-client@dev-master`, because I have not created a release. But you should take a look at the library that @malle-pietje suggests.
